### PR TITLE
Replace timestamp with @timestamp

### PR DESCRIPTION
**Pull request by monicasarbu**
* [x] change `timestamp` with `@timestamp` in the code and tests
* [x] update docs
* [x] update changelog

### CODE REVIEW

**Comment by monicasarbu** [comment]
@urso Currently this fix makes the tests related to the logstash input plugin fail. Would be possible to test if it's working before merging the PR?

**Comment by urso** [comment]
requires logstash-plugins/logstash-input-beats/pull#10 plus updated gem to fix tests.

**Comment by ruflin** [comment]
https://github.com/logstash-plugins/logstash-input-beats/pull/10 is now merged.

**Comment by urso** [comment]
@monicasarbu can you rebase? the merging on CHANGELOG.md is not working with github anymore.

**Pull request merged**
