### PR TITLE
Cache: optional per element timeout

### PR DESCRIPTION
**Pull request by urso**
Configure per element timeout in cache. If element timeout is <=0, the
cache its default timeout will be used.

required for elastic/packetbeat#300

### CODE REVIEW

**Comment by tsg** [comment]
There was a discussion on Hipchat about this one, with the following options mentioned:

* provide a `cache.DefaultTimeout` constant for the caller to use instead of 0
* use the var args trick to simulate an optional parameter so you can call `cache.Put(k, v)`, or `Put(k, v, common.Timeout(....))`
* add another `PutWithTimeout(k, v, timeout)` function

My opinion is the last option would be the most idiomatic Go thing to do, but I defer to @urso and @andrewkroh  for the decision.

**Comment by urso** [comment]
I will go for option 3.

**Comment by McStork** [comment]
@urso Could it be possible to set timeout to 0 ? For the use case we have we don't need to link queries with responses; and we might not be the only ones in this situation.

**Comment by urso** [comment]
@McStork timeout of 0 should be invalid. All application layer module correlate requests to responses. You use-case of basically just parsing messages is not support by packetbeat, but if it can not correlate a request to a response, it can still publish the messages.

**Comment by McStork** [comment]
Alright. We actually want to log all the incoming packets, but not the reponses. I set a low timeout so it can publish faster to ES. It's just too bad we cannot disable the correlation request <-> response.

**Comment by urso** [comment]
@McStork feel free to create an enhancement request on packetbeat to start some discussion (not everyone will follow this ticket here).

**Pull request merged**
