### PR TITLE
Use the Beat name in the default configuration file path

### LINKED ISSUE #66: Make sure default config is named the same as beat name
See also https://github.com/elastic/libbeat/pull/65/files#r39164410

### PR DESCRIPTION
**Pull request by tsg**
Adds a bit of extra complexity but fortunately requires no changes to the Beats, it's a change internal in libbeat.

Should fix #66.

### CODE REVIEW

**Comment by tsg** [comment]
@ruflin I'd like your review on this one. Others are welcome as well, ofc.

**Comment by monicasarbu** [comment]
LGTM

**Comment by ruflin** [comment]
@tsg This will unfortunately not work with our system tests as the flag must be defined either in the init() function or outside the methods.

**Comment by tsg** [comment]
What does "outside the methods" mean more exactly? Global?

**Comment by ruflin** [comment]
Yes. The better definition is it must run before the main() function runs. This is the case for all init() functions.

**Comment by tsg** [comment]
Came up with a better solution, which works for the coverage-enabled system tests binary. One caveat is that this binary now has a different default value when compared with the regular binary, but that doesn't affect our tests.

**Pull request merged**
