### PR TITLE
Event Channel as part of Beat

### PR DESCRIPTION
**Pull request by ruflin**
The documentation will be updated in a second step as soon as topbeat and packetbeat are updated.

See https://github.com/elastic/libbeat/issues/44

### CODE REVIEW

**Comment by ruflin** [comment]
There seems to be an issue with this change. Please don't merge yet.

**Comment by urso** [comment]
Instead of passing a channel how about using an interface having a publish method. Makes it easier to swap the publisher in unit tests for example (have unit test publisher which just collects all events in an array)

**Comment by ruflin** [comment]
@urso I agree we should refactor this. I fixed it in the above commit by just assigning it after the init phase.

**Comment by urso** [comment]
+1

**Pull request merged**
